[0m[[0m[31merror[0m] [0m[0mjava.lang.Exception: Not supported : equation are the same[0m
[0m[[0m[31merror[0m] [0m[0m	at Particle.willCollideAt$1(Solution.scala:66)[0m
[0m[[0m[31merror[0m] [0m[0m	at Particle.willCollideAt(Solution.scala:69)[0m
[0m[[0m[31merror[0m] [0m[0m	at Solution$package$$anon$2.applyOrElse(Solution.scala:159)[0m
[0m[[0m[31merror[0m] [0m[0m	at Solution$package$$anon$2.applyOrElse(Solution.scala:159)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.Iterator$$anon$7.hasNext(Iterator.scala:525)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:601)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.immutable.List.prependedAll(List.scala:152)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.IterableOnceOps.toList(IterableOnce.scala:1288)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.IterableOnceOps.toList$(IterableOnce.scala:1288)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.AbstractIterator.toList(Iterator.scala:1300)[0m
[0m[[0m[31merror[0m] [0m[0m	at Solution$package$.findNonColliding2(Solution.scala:161)[0m
[0m[[0m[31merror[0m] [0m[0m	at Solution$.run(Solution.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at Solver$.runOn(Main.scala:22)[0m
[0m[[0m[31merror[0m] [0m[0m	at Solver$.solver(Main.scala:35)[0m
[0m[[0m[31merror[0m] [0m[0m	at Solver$.solveTest(Main.scala:27)[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$package$.hello$$anonfun$1(Main.scala:12)[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$package$.hello$$anonfun$3(Main.scala:13)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.collection.immutable.List.foreach(List.scala:333)[0m
[0m[[0m[31merror[0m] [0m[0m	at Main$package$.hello(Main.scala:16)[0m
[0m[[0m[31merror[0m] [0m[0m	at hello.main(Main.scala:8)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.reflect.Method.invoke(Method.java:568)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:144)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:94)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:187)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:121)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1988)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1927)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:367)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:840)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) java.lang.Exception: Not supported : equation are the same[0m
